In [1]:
import numpy as np
import pandas as pd

In [3]:
marks = pd.Series([85,90,78,92])
print(marks)

0    85
1    90
2    78
3    92
dtype: int64

In [4]:
arr = np.array([10,220,550])
s = pd.Series(arr)
print(s)

0     10
1    220
2    550
dtype: int64

In [15]:
marks = pd.Series([85,90,78,92], index=['Maths','Science','Art','History'])
print(marks)

marks.head(2)

marks.sum()

marks.sort_values()

marks.unique()

def func(n):
    print(n*2)

marks.apply(func)

Maths      85
Science    90
Art        78
History    92
dtype: int64
170
180
156
184

Maths      None
Science    None
Art        None
History    None
dtype: object

In [36]:
records = [
    {'Name':'aditi','Age':21},
    {'Name':'rohan','Age':23},
    {'Name':'kiran'},
]

df = pd.DataFrame(records)
print(df)

    Name   Age
0  aditi  21.0
1  rohan  23.0
2  kiran   NaN

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [19]:
df.describe()

             Age
count   2.000000
mean   22.000000
std     1.414214
min    21.000000
25%    21.500000
50%    22.000000
75%    22.500000
max    23.000000

In [21]:
df.shape

(2, 2)

In [23]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [24]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [25]:
df.dtypes

Name    object
Age      int64
dtype: object

In [26]:
df.isnull()

    Name    Age
0  False  False
1  False  False

In [34]:
df.isnull().sum()

Name    0
Age     1
dtype: int64

In [28]:
df.notnull()

   Name   Age
0  True  True
1  True  True

In [35]:
df.dropna()

    Name   Age
0  aditi  21.0
1  rohan  23.0

In [37]:
df['Age'] = df['Age'].fillna(0)

In [38]:
print(df)

    Name   Age
0  aditi  21.0
1  rohan  23.0
2  kiran   0.0

In [41]:
df['Name'] = df['Name'].replace({'aditi':'aditya'})
print(df)

     Name   Age
0  aditya  21.0
1   rohan  23.0
2   kiran   0.0

In [42]:
df.sort_values('Age')

     Name   Age
2   kiran   0.0
0  aditya  21.0
1   rohan  23.0

In [45]:
df['eligible'] = df['Age'] > 18
print(df)

     Name   Age  eligible
0  aditya  21.0      True
1   rohan  23.0      True
2   kiran   0.0     False